version: "3.4"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8182"      
    environment:
      - PROXY_CLIENT_ID
      - PROXY_CLIENT_SECRET
      - PROXY_DISCOVERY_URL
      - PROXY_SECURE_COOKIE

  tester:
    build:
      context: ./
      dockerfile: Dockerfile
      target: tester
