version: "3.4"
services:
  server:
    image: docker-registry.data.amsterdam.nl/datapunt/iiif-image-server:${VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    environment:
      - USE_LOCAL_SOURCE=true
    volumes:
      - ./upgrade_cantaloupe_version.sh:/app/cantaloupe/upgrade_cantaloupe_version.sh
      - ./Dockerfile:/app/cantaloupe/Dockerfile

  tester:
    build:
      context: ./
      dockerfile: Dockerfile
      target: tester
      args:
      - JRUBY_VERSION=9.3.7.0  # Upgrade when you feel like it is time
    environment:
      - USE_LOCAL_SOURCE=false
