version: "3.4"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    environment:
      - USE_LOCAL_SOURCE=true
      - START_STUNNEL=false
      - IIIF_IMAGE_SERVER_WABO_CERT=dGhlIGNvbnRlbnRzIG9mIHRoZSBjZXJ0IGZpbGU=  # This says "the contents of the cert file"

  tester:
    build:
      context: ./
      dockerfile: Dockerfile
      target: tester
    environment:
      - USE_LOCAL_SOURCE=false
