# Config file for gatekeeper proxy
# See https://www.keycloak.org/docs/latest/securing_apps/index.html#_keycloak_generic_adapter

# The following is either secret or environment dependent:
# * secure-cookie
# * client_id
# * client_secret
# * discovery_url
#
# You can set them using environment variables (in an .env file for example):
# * PROXY_SECURE_COOKIE=false
# * PROXY_CLIENT_ID
# * PROXY_CLIENT_SECRET
# * GATEKEEPER_DISCOVERY_URL, e.g.: https://iam.amsterdam.nl/auth/realms/datapunt-acc

enable-default-deny: true
listen: 0.0.0.0:8080
#redirection-url: http://127.0.0.1:8080
upstream-url: http://127.0.0.1:8182
verbose: true
secure-cookie: true # set this to false for local dev
resources:
- uri: /*
  roles:
  - edepot_public
  - edepot_private
  require-any-role: true # Match at least one of the roles

# Allow health check to pass
- uri: / # Root only!
  white-listed: true
- uri: /favicon.ico
  white-listed: true
- uri: /static/styles/landing.css
  white-listed: true
- uri: /static/images/cantaloupe-320.png
  white-listed: true
