# Config file for gatekeeper proxy
# See https://www.keycloak.org/docs/latest/securing_apps/index.html#_keycloak_generic_adapter

# The following is either secret or environment dependent:
# * client_id
# * client_secret
# * discovery_url
#
# You can set them using environment variables:
# * PROXY_CLIENT_ID
# * PROXY_CLIENT_SECRET
# * GATEKEEPER_DISCOVERY_URL, e.g.: https://iam.amsterdam.nl/auth/realms/datapunt-acc

enable-default-deny: true
listen: 0.0.0.0:8080
#redirection-url: http://127.0.0.1:8080
upstream-url: http://127.0.0.1:8182
#resources:
#- uri: /admin*
#  methods:
#  - GET
#  roles:
#  - client:test1
#  - client:test2
#  require-any-role: true
#  groups:
#  - admins
#  - users
#- uri: /backend*
#  roles:
#  - client:test1
#- uri: /public/*
#  white-listed: true
#headers:
#  myheader1: value_1
#  myheader2: value_2

